version: '3.8'

services:
  db:
    image: postgres:14.4
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql